name: find-changes

on:
  pull_request:
  push:

jobs:
  find-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: Oksi-D/md-sa2-23-23-github
          path: md-sa2-23-23-github
      - name: Get changed files
        run: |
          changed_files=$(git diff HEAD HEAD~1)
          echo "::set-output name=files::$changed_files"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: changes-info
          path: |
            changed_files.txt
