name: find-changes

on:
  pull_request:
  push:

jobs:
  find-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get changed files
        run: |
          git fetch git@github.com:OksanaDemidovec/md-sa2-23-23-github-1.git ${{ github.head_ref }}
          changed_files=$(git diff --name-only git@github.com:OksanaDemidovec/md-sa2-23-23-github-1.git/${{ github.head_ref }}...HEAD)
          echo "::set-output name=files::$changed_files"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: changes-info
          path: |
            changed_files.txt
