name: find-changes

on: pull_request

jobs:
  find-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get changed files
        run: |
          git fetch origin ${{ github.head_ref }}
          changed_files=$(git diff --name-only origin/${{ github.head_ref }}...HEAD)
          echo "::set-output name=files::$changed_files"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: changes-info
          path: |
            changed_files.txt
            #tabs_count.txt
