name: Tab search in changed files on PR

on:
  pull_request:
  
jobs:
  find-changes:
    runs-on: ubuntu-latest
    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            count=$(grep -o $'\t' "$changed_file" | wc -l)
            echo "Количество табуляций в файле $changed_file: $count"
            total_count=$((total_count + count))
          done
          echo "$total_count" >> changed_files.txt
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: changes-info
          path: |
            changed_files.txt
